services:
  db:
    image: postgres:15-alpine
    container_name: gardenkeep-db
    environment:
      POSTGRES_DB: gardenkeep_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: